name: Update On Merge

on:
  push:
    branches:
      - main

jobs:
  update-on-merge:
    runs-on: [self-hosted, nifi]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: /home/ec2-user/nifi/repositorios/prod
